

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 18

[window]
opacity = 0.8
blur = true
padding.x = 10
padding.y = 10
decorations = "Buttonless"

[env]
TERM = "xterm-256color"
